== Stories and Metaphors

Leader::

_Why is this seder different from most other seders?_
+
The story of Passover is a deep part of Jewish culture, and it contains many
truths about humanity and Judaism which are important to carry forward.
+
Archeologists, historians, and religious scholars all tell us that the story
of Exodus is best seen as metaphor and not history — we were never literally
slaves in Egypt. But ancient and modern times are filled with real histories,
from the Inquisition and diaspora of 15th century Europe to the Russian
pogroms that drove some of our recent ancestors to this country.
+
Most of all, through the personal histories of family and friends, our own
lives are still touched by the events of the Holocaust — a time in which three
times as many Jews were murdered as were alive in the time of Exodus. While
here today we are free to celebrate the Passover in whatever way tradition and
personal preference dictate, people in other parts of the world may not be so
fortunate. While we sing, others still weep; while we recline like kings,
others are still in bondage.
+
So we must remember that the story of Passover, as told in Exodus and most
Haggadahs, is not a literal retelling of past events. We must remember that
when we tell this story about slavery and freedom, we would do an injustice to
make that story about Pharaohs and Egyptians, in exactly the same way that
others have for centuries done Jews injustice when they tell false stories
about our culture and our doings.
+
So tonight, we try to tell a story about freedom for _all_ people -- Egyptians
included.


