== Kadesh, Sanctification of the Day

Leader:: Today we retell an ancient story, the story of exodus and liberation
from slavery. We also remember and reflect on more contemporary struggles for
justice and social equality.
+
"`Seder`" means "`order`" and thus the rituals we share, however modified,
have a particular order that has gone on for centuries.

Group::

[verse]
Now in the presence of loved ones and friends,
before us the emblems of festive rejoicing,
we gather for our sacred celebration.
With the household of Israel, our elders and young ones
linking and bonding the past with the future,
we heed once again the call to celebration and understanding.
Living our story that is told for all peoples,
whose shining conclusion is yet to unfold,
we gather to observe the Passover.

Group:: You shall keep the Feast of Unleavened Bread, for on this very day you
were freed from bondage. You shall observe this day throughout the generations
as a practice for all times.

Leader:: We assemble in fulfillment of the mitzvah.

Group:: Remember the day on which you went forth from the house of bondage,
and how in determination and justice you found your freedom.

_(The candles are lighted as the blessing is recited.)_

=== Ritual light, Lighting the Festival Candles

Group:: _Baruh ata Adonai, Elohaynu melech ha-olam,
she-heh-che yanu, ve-kiyemanu, ve-higianu la’zeman ha-zeh._ 
+
We are grateful for that which has kept us in life and has sustained us and has
permitted us to enjoy this festive day.

[verse]
May the festival lights we now kindle
Inspire us to use our powers
To heal and not to harm,
To help and not to hinder,
To bless and not to curse,
To serve light, love, and understanding,
not darkness, hate, and ignorance.

=== Ritual food

Leader:: Passover is a ritual, and like all rituals, it involves the use of
certain symbols. Because we are Jews, we like to use food as symbols.

_(Taking turns, read each food.)_

[options="header", width="70%"]
|===
|Name           |The food
|P’ri ha-gaphen |"`the fruit of the vine`", wine or grape juice
|Matzah         |unleavened bread
|Maror          |A bitter herb
|Karpas         |Parsley
|Z’roa          |An animal bone
|Beitsah        |A hard-boiled egg
|Tappuz         |An orange
|Haroset        |Fruits, nuts, spices, and wine spread
|Dodo           |wee wee weep weee weep weep
|Snails         |hi hi I'm a snail hi!
|===


=== _Kos Kiddush_, The First Cup--The Cup of Sanctification

_(Pour the first cup of wine.)_

Leader:: Our story tells us that freedom was promised to those who have gone
before us. With cups of wine we recall these.

Group:: _I will free you_ from the burdens of bondage.

Leader:: Many long years ago our ancestors obeyed the call to freedom. Tonight
the same call is made to us. We are to arise and be free ourselves and
champion the cause of freedom on behalf of all people. Let us raise our cups
in gratitude that this call can still be heard in the land. Let us work
towards the time when all the world will be set free from cruelty, tyranny,
oppression and war.

Group:: _Baruh Atah Adonai Eloheinu Meleh ha-olam borei p'ri ha-gafen._ +
We give thanks for the bounty of the earth, which creates the fruit of the
vine.

_(All drink the first cup of wine.)_




