== Yachatz, A Bond Formed By Sharing

One:: Matzah is known as the "`bread of poverty.`" One reason we break the
middle matzah in a traditional seder is to show that the poor need to set
aside some of their food for the next meal.
+
This is the bread representing affliction and poverty. May whoever is hungry
come and eat. May anyone who is in distress come and celebrate with us.

Group::  When we call out '`Let all who are hungry come and eat,`' may there be
no one in the world who needs to come in!
+
We acknowledge the people who have struggled in poverty for
generations and the newly poor in this country and abroad.

[verse]
This is the bread of affliction
the poor bread,
which our ancestors have eaten and theirs before them.
Let all who are hungry come and eat.
Let all who are in want
share the hope of Passover.
As we celebrate here,
we join with people everywhere.
This year we celebrate here.
Next year in a place still more free.
Now we are all still in chains.
Next year may all be free.

=== The Afikomen

One:: Tonight we will also set aside the Afikomen, the matzah that is
traditionally eaten at the end of the meal. Later, when the children search for
the Afikomen, it reminds us that no people who work to seek and remember can
ever be lost or destroyed. The Afikomen also reminds us, the adults, that our
children have a right to be heard.

_(Break half and put in pouch.)_

